apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-streaming-app.fullname" . }}
  labels:
    {{- include "simple-streaming-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-streaming-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simple-streaming-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simple-streaming-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: client-credentials
                  key: bootstrap-server
            - name: CLUSTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: client-credentials
                  key: cluster-api-key
            - name: CLUSTER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-credentials
                  key: cluster-api-secret
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: client-credentials
                  key: schema-registry-url
            - name: SCHEMA_REGISTRY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: client-credentials
                  key: schema-registry-api-key
            - name: SCHEMA_REGISTRY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-credentials
                  key: schema-registry-api-secret
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
